const mongoose = require("mongoose");
const db = require("../models");

// This file empties the database and inserts new users and snips.
mongoose.connect(
  process.env.MONGODB_URI || "mongodb://localhost/hallOfGreatsDB",
  {
    useNewUrlParser: true,
    useFindAndModify: false,
    useUnifiedTopology: true,
  }
);
const winnerSeed = [
  {
    hallOfGreatsOne: {
      gameOne: {
        name: "Metal Gear Solid",
        image: "",
        description: "",
        genre: "Action Adventure",
        year: 1998,
        platforms: "Playstation One",
        metacritic: 94,
        nominatedBy: "Michael Damiani",
        votes: 10,
      },
      gameTwo: {
        name: "Super Metroid",
        image: "",
        description: "",
        genre: "Metroidvania",
        year: 1994,
        platforms: "Super NES",
        metacritic: "-",
        nominatedBy: "Daniel Bloodworth",
        votes: 9,
      },
    },
    hallOfGreatsTwo: {
      gameOne: {
        name: "Super Mario 64",
        image: "",
        description: "",
        genre: "Platformer",
        year: 1996,
        platforms: "Nintendo 64",
        metacritic: 94,
        nominatedBy: "Michael Damiani & Brad Ellis",
        votes: 15,
      },
      gameTwo: {
        name: "Street Fighter II",
        image: "",
        description: "",
        genre: "Fighting",
        year: "1992",
        platforms: "Arcade & Super NES",
        metacritic: "-",
        nominatedBy: "Daniel Bloodworth",
        votes: 14,
      },
    },
    hallOfGreatsThree: {
      gameOne: {
        name: "The Legend of Zelda: Ocarina of Time",
        image: "",
        description: "",
        genre: "Action-Adventure",
        year: 1998,
        platforms: "Nintendo 64",
        metacritic: 99,
        nominatedBy: "Michael Damiani",
        votes: 16,
      },
      gameTwo: {
        name: "Castlevania: Symphony of the Night",
        image: "",
        description: "",
        genre: "Metroidvania",
        year: 1997,
        platforms: "Playstation One",
        metacritic: 93,
        nominatedBy: "Ian Hinck",
        votes: 11,
      },
    },
    hallOfGreatsFour: {
      gameOne: {
        name: "Chrono Trigger",
        image: "",
        description: "",
        genre: "Role-Playing Game",
        year: 1995,
        platforms: "Super NES",
        metacritic: 96,
        nominatedBy: "Brad Ellis",
        votes: 21,
      },
      gameTwo: {
        name: "Pokemon Red & Blue",
        image: "",
        description: "",
        genre: "Role-Playing Game",
        year: 1998,
        platforms: "Gameboy",
        metacritic: 88,
        nominatedBy: "Kyle Bosman",
        votes: 8,
      },
    },
    hallOfGreatsFive: {
      gameOne: {
        name: "Resident Evil 4",
        image: "",
        description:
          "Resident Evil 4 marks a new chapter in the Resident Evil series. You'll rejoin Leon S. Kennedy six years after his first mission as a rookie cop from Resident Evil 2. Now a US agent, Leon is on a top secret mission to investigate the disappearance of the president's daughter. As Leon, you must make your way to a mysterious location in Europe, where new enemies await. Take them down by using enhanced aim-and-shoot features and a new action button.",
        genre: "Survival Horror",
        year: 2005,
        platforms: "Nintendo Gamecube",
        metacritic: 96,
        nominatedBy: "Brad Ellis",
        votes: 13,
      },
      gameTwo: {
        name: "Resident Evil Remake",
        image: "",
        description: "",
        genre: "Survival Horror",
        year: 2002,
        platforms: "Nintendo Gamecube",
        metacritic: 91,
        nominatedBy: "Ben Moore",
        votes: 11,
      },
    },
    hallOfGreatsSix: {
      gameOne: {
        name: "Metroid Prime",
        image: "",
        description: "",
        genre: "Metroidvania",
        year: 2002,
        platforms: "Nintendo Gamecube",
        metacritic: 97,
        nominatedBy: "Michael Damiani",
        votes: 19,
      },
      gameTwo: {
        name: "Paper Mario & The Thousand-Year Door",
        image: "",
        description: "",
        genre: "Role-Playing Game",
        year: 2004,
        platforms: "Nintendo Gamecube",
        metacritic: 87,
        nominatedBy: "Ben Moore",
        votes: 12,
      },
    },
    hallOfGreatsSeven: {
      gameOne: {
        name: "Final Fantasy VI",
        image: "",
        description: "",
        genre: "Role-Playing Game",
        year: 1994,
        platforms: "Super NES",
        metacritic: 94,
        nominatedBy: "Brandon Jones",
        votes: 13,
      },
      gameTwo: {
        name: "Tetris",
        image: "",
        description: "",
        genre: "Puzzle",
        year: 1989,
        platforms: "",
        metacritic: "-",
        nominatedBy: "Kyle Bosman",
        votes: 13,
      },
    },
    hallOfGreatsEight: {
      gameOne: {
        name: "Bloodborne",
        image: "",
        description: "",
        genre: "Action Role-Playing Game",
        year: 2015,
        platforms: "Playstation 4",
        metacritic: 92,
        nominatedBy: "Ian Hinck",
        votes: 13,
      },
      gameTwo: {
        name: "Portal",
        image: "",
        description: "",
        genre: "Puzzle",
        year: 2007,
        platforms: "PC",
        metacritic: 90,
        nominatedBy: "Brandon Jones",
        votes: 11,
      },
    },
    hallOfGreatsNine: {
      gameOne: {
        name: "The Legend of Zelda: A Link to the Past",
        image: "",
        description: "",
        genre: "Action-Adventure",
        year: 1991,
        platforms: "Super NES",
        metacritic: 92,
        nominatedBy: "Michael Damiani",
        votes: 13,
      },
      gameTwo: {
        name: "Super Mario Bros. 3",
        image: "",
        description: "",
        genre: "Platformer",
        year: 1988,
        platforms: "NES",
        metacritic: 97,
        nominatedBy: "Kyle Bosman",
        votes: 12,
      },
    },
    hallOfGreatsTen: {
      gameOne: {
        name: "The Last of Us",
        image: "",
        description:
          "Twenty years after a pandemic radically transformed known civilization, infected humans run amuck and survivors kill one another for sustenance and weapons - literally whatever they can get their hands on. Joel, a salty survivor, is hired to smuggle a fourteen-year-old girl, Ellie, out of a rough military quarantine, but what begins as a simple job quickly turns into a brutal journey across the country.",
        genre: "Action-Adventure",
        year: 2013,
        platforms: "Playstation 3",
        metacritic: 95,
        nominatedBy: "Michael Huber",
        votes: 8,
      },
      gameTwo: {
        name: "The Witcher III: The Wild Hunt",
        image: "",
        description: "",
        genre: "Action Role-Playing Game",
        year: 2015,
        platforms: "Playstation 4, Xbox One, PC",
        metacritic: 92,
        nominatedBy: "Daniel Bloodworth",
        votes: 8,
      },
    },
    hallOfGreatsEleven: {
      gameOne: {
        name: "Counter-Strike",
        image: "",
        description: "",
        genre: "First-Person Shooter",
        year: 2000,
        platforms: "PC",
        metacritic: 88,
        nominatedBy: "Ben Moore",
        votes: 12,
      },
      gameTwo: {
        name: "Final Fantasy VII",
        image: "",
        description: "",
        genre: "Role-Playing Game",
        year: 1997,
        platforms: "Playstation One",
        metacritic: 92,
        nominatedBy: "Brad Ellis",
        votes: 13,
      },
    },
    hallOfGreatsTwelve: {
      gameOne: {
        name: "World of Warcraft",
        image: "",
        description: "",
        genre: "MMO Role-Playing Game",
        year: 2004,
        platforms: "PC",
        metacritic: 93,
        nominatedBy: "Brandon Jones",
        votes: 14,
      },
      gameTwo: {
        name: "The Ultimate Doom",
        image: "",
        description: "",
        genre: "First-Person Shooter",
        year: 1995,
        platforms: "PC",
        metacritic: 91,
        nominatedBy: "Ben Moore",
        votes: 11,
      },
    },
    hallOfGreatsThirteen: {
      gameOne: {
        name: "Donkey Kong Country: Tropical Freeze",
        image: "",
        description: "",
        genre: "Platformer",
        year: 2014,
        platforms: "Nintendo Wii U & Nintendo Switch",
        metacritic: 86,
        nominatedBy: "Brad Ellis",
        votes: 14,
      },
      gameTwo: {
        name: "Yakuza 0",
        image: "",
        description: "",
        genre: "Action-Adventure",
        year: 2017,
        platforms: "Playstation 4, Xbox One, PC",
        metacritic: 85,
        nominatedBy: "Michael Huber",
        votes: 12,
      },
    },
  },
];

const nominationSeed = [
  {
    allyOne: {
      nominator: "Don Casanova",
      gameOne: {
        game: "Assassins Creed IV: Black Flag",
        hallOfGreat: 1,
        votesGiven: 2,
        victory: false,
        banned: false,
      },
      gameTwo: {
        game: "Sim City 4",
        hallOfGreat: 2,
        votesGiven: 1,
        victory: false,
        banned: true,
      },
      gameThree: {
        game: "Jurassic Park: Operations Genesis",
        hallOfGreat: 3,
        votesGiven: 2,
        victory: false,
        banned: true,
      },
      gameFour: {
        game: "Super Mario Maker",
        hallOfGreat: 4,
        votesGiven: 3,
        victory: false,
        banned: true,
      },
      gameFive: {
        game: "Pandemonium",
        hallOfGreat: 5,
        votesGiven: 4,
        victory: false,
        banned: false,
      },
      gameSix: {
        game: "Sim City 4",
        hallOfGreat: 6,
        votesGiven: 3,
        victory: false,
        banned: false,
      },
      gameSeven: {
        game: "Mortal Kombat 2011",
        hallOfGreat: 7,
        votesGiven: 8,
        victory: false,
        banned: false,
      },
      gameEight: {
        game: "Trials Fusion",
        hallOfGreat: 8,
        votesGiven: 6,
        victory: false,
        banned: false,
      },
      gameNine: {
        game: "Wave Race 64",
        hallOfGreat: 9,
        votesGiven: 3,
        victory: false,
        banned: false,
      },
      gameTen: {
        game: "Burnout 3: Takedown",
        hallOfGreat: 10,
        votesGiven: 5,
        victory: false,
        banned: false,
      },
      gameEleven: {
        game: "Aliens vs. Predator",
        hallOfGreat: 11,
        votesGiven: 12,
        victory: false,
        banned: false,
      },
      gameTwelve: {
        game: "Huntdown",
        hallOfGreat: 13,
        votesGiven: 0,
        victory: false,
        banned: true,
      },
    },
    allyTwo: {
      nominator: "Brandon Jones",
      gameOne: {
        game: "Goldeneye 007",
        hallOfGreat: 1,
        votesGiven: 1,
        victory: false,
        banned: false,
      },
      gameTwo: {
        game: "World of Warcraft",
        hallOfGreat: 2,
        votesGiven: 1,
        victory: false,
        banned: true,
      },
      gameThree: {
        game: "Half-Life 2",
        hallOfGreat: 3,
        votesGiven: 5,
        victory: false,
        banned: false,
      },
      gameFour: {
        game: "Grand Theft Auto III",
        hallOfGreat: 4,
        votesGiven: 7,
        victory: false,
        banned: false,
      },
      gameFive: {
        game: "Pong",
        hallOfGreat: 5,
        votesGiven: 2,
        victory: false,
        banned: false,
      },
      gameSix: {
        game: "Grand Theft Auto V",
        hallOfGreat: 6,
        votesGiven: 1,
        victory: false,
        banned: false,
      },
      gameSeven: {
        game: "Final Fantasy VI",
        hallOfGreat: 7,
        votesGiven: 13,
        victory: true,
        banned: false,
      },
      gameEight: {
        game: "Portal",
        hallOfGreat: 8,
        votesGiven: 11,
        victory: true,
        banned: false,
      },
      gameNine: {
        game: "Goldeneye 007",
        hallOfGreat: 9,
        votesGiven: 0,
        victory: false,
        banned: true,
      },
      gameTen: {
        game: "Plants vs. Zombies",
        hallOfGreat: 11,
        votesGiven: 1,
        victory: false,
        banned: false,
      },
      gameEleven: {
        game: "World of Warcraft",
        hallOfGreat: 12,
        votesGiven: 14,
        victory: true,
        banned: false,
      },
      gameTwelve: {
        game: "Journey",
        hallOfGreat: 13,
        votesGiven: 6,
        victory: false,
        banned: false,
      },
    },
    allyThree: {
      nominator: "Brad Ellis",
      gameOne: {
        game: "Dark Souls",
        hallOfGreat: 1,
        votesGiven: 1,
        victory: false,
        banned: false,
      },
      gameTwo: {
        game: "Super Mario 64",
        hallOfGreat: 2,
        votesGiven: 15,
        victory: true,
        banned: false,
      },
      gameThree: {
        game: "Doom 2016",
        hallOfGreat: 3,
        votesGiven: 0,
        victory: false,
        banned: true,
      },
      gameFour: {
        game: "Chrono Trigger",
        hallOfGreat: 4,
        votesGiven: 21,
        victory: true,
        banned: false,
      },
      gameFive: {
        game: "Resident Evil 4",
        hallOfGreat: 5,
        votesGiven: 13,
        victory: true,
        banned: false,
      },
      gameSix: {
        game: "Donkey Kong Country: Tropical Freeze",
        hallOfGreat: 6,
        votesGiven: 2,
        victory: false,
        banned: false,
      },
      gameSeven: {
        game: "Bloodborne",
        hallOfGreat: 7,
        votesGiven: 9,
        victory: false,
        banned: false,
      },
      gameEight: {
        game: "God of War 2018",
        hallOfGreat: 8,
        votesGiven: 11,
        victory: false,
        banned: false,
      },
      gameNine: {
        game: "The Legend of Zelda: Twilight Princess",
        hallOfGreat: 9,
        votesGiven: 6,
        victory: false,
        banned: false,
      },
      gameTen: {
        game: "Final Fantasy VII",
        hallOfGreat: 11,
        votesGiven: 13,
        victory: true,
        banned: false,
      },
      gameEleven: {
        game: "Shovel Knight: Treasure Trove",
        hallOfGreat: 12,
        votesGiven: 4,
        victory: false,
        banned: false,
      },
      gameTwelve: {
        game: "Donkey Kong Country: Tropical Freeze",
        hallOfGreat: 13,
        votesGiven: 14,
        victory: true,
        banned: false,
      },
    },
    allyFour: {
      nominator: "Daniel Bloodworth",
      gameOne: {
        game: "Super Metroid",
        hallOfGreat: 1,
        votesGiven: 9,
        victory: true,
        banned: false,
      },
      gameTwo: {
        game: "Street Fighter II",
        hallOfGreat: 2,
        votesGiven: 14,
        victory: true,
        banned: false,
      },
      gameThree: {
        game: "Portal",
        hallOfGreat: 3,
        votesGiven: 4,
        victory: false,
        banned: false,
      },
      gameFour: {
        game: "Journey",
        hallOfGreat: 4,
        votesGiven: 2,
        victory: false,
        banned: false,
      },
      gameFive: {
        game: "Dark Souls",
        hallOfGreat: 5,
        votesGiven: 7,
        victory: false,
        banned: false,
      },
      gameSix: {
        game: "Dragon Quest VIII",
        hallOfGreat: 6,
        votesGiven: 7,
        victory: false,
        banned: false,
      },
      gameSeven: {
        game: "Ms. Pacman",
        hallOfGreat: 7,
        votesGiven: 0,
        victory: false,
        banned: true,
      },
      gameEight: {
        game: "Deus Ex",
        hallOfGreat: 8,
        votesGiven: 0,
        victory: false,
        banned: true,
      },
      gameNine: {
        game: "The Witcher III: The Wild Hunt",
        hallOfGreat: 10,
        votesGiven: 8,
        victory: true,
        banned: false,
      },
      gameTen: {
        game: "Animal Crossing",
        hallOfGreat: 11,
        votesGiven: 3,
        victory: false,
        banned: false,
      },
      gameEleven: {
        game: "Guitar Hero II",
        hallOfGreat: 12,
        votesGiven: 2,
        victory: false,
        banned: false,
      },
      gameTwelve: {
        game: "Katamari Damacy",
        hallOfGreat: 13,
        votesGiven: 4,
        victory: false,
        banned: false,
      },
    },
    allyFive: {
      nominator: "Michael Huber",
      gameOne: {
        game: "Resident Evil Remake",
        hallOfGreat: 1,
        votesGiven: 0,
        victory: false,
        banned: false,
      },
      gameTwo: {
        game: "Dragon Quest VIII",
        hallOfGreat: 2,
        votesGiven: 5,
        victory: false,
        banned: false,
      },
      gameThree: {
        game: "The Last of Us",
        hallOfGreat: 3,
        votesGiven: 4,
        victory: false,
        banned: false,
      },
      gameFour: {
        game: "Streets of Rage 2",
        hallOfGreat: 4,
        votesGiven: 4,
        victory: false,
        banned: false,
      },
      gameFive: {
        game: "The Witcher III: The Wild Hunt",
        hallOfGreat: 5,
        votesGiven: 9,
        victory: false,
        banned: false,
      },
      gameSix: {
        game: "Time Crisis 2",
        hallOfGreat: 6,
        votesGiven: 1,
        victory: false,
        banned: false,
      },
      gameSeven: {
        game: "Batman: Arkham City",
        hallOfGreat: 7,
        votesGiven: 3,
        victory: false,
        banned: false,
      },
      gameEight: {
        game: "The Last of Us",
        hallOfGreat: 8,
        votesGiven: 3,
        victory: false,
        banned: false,
      },
      gameNine: {
        game: "Sekiro: Shadows Die Twice",
        hallOfGreat: 9,
        votesGiven: 3,
        victory: false,
        banned: false,
      },
      gameTen: {
        game: "The Last of Us",
        hallOfGreat: 10,
        votesGiven: 8,
        victory: true,
        banned: false,
      },
      gameEleven: {
        game: "Marvels Spider-Man",
        hallOfGreat: 11,
        votesGiven: 2,
        victory: false,
        banned: false,
      },
      gameTwelve: {
        game: "Super Smash Brothers. Ultimate",
        hallOfGreat: 12,
        votesGiven: 6,
        victory: false,
        banned: false,
      },
      gameThirteen: {
        game: "Yakuza 0",
        hallOfGreat: 13,
        votesGiven: 12,
        victory: true,
        banned: false,
      },
    },
    allySix: {
      nominator: "Ben Moore",
      gameOne: {
        game: "Street Fighter II Turbo",
        hallOfGreat: 1,
        votesGiven: 9,
        victory: false,
        banned: false,
      },
      gameTwo: {
        game: "Valkyria Chronicles",
        hallOfGreat: 2,
        votesGiven: 1,
        victory: false,
        banned: false,
      },
      gameThree: {
        game: "Xenoblade Chronicles",
        hallOfGreat: 3,
        votesGiven: 3,
        victory: false,
        banned: false,
      },
      gameFour: {
        game: "Mega Man X",
        hallOfGreat: 4,
        votesGiven: 7,
        victory: false,
        banned: false,
      },
      gameFive: {
        game: "Resident Evil Remake",
        hallOfGreat: 5,
        votesGiven: 11,
        victory: true,
        banned: false,
      },
      gameSix: {
        game: "Paper Mario & The Thousand-Year Door",
        hallOfGreat: 6,
        votesGiven: 12,
        victory: true,
        banned: false,
      },
      gameSeven: {
        game: "Halo: Combat Evolved",
        hallOfGreat: 7,
        votesGiven: 3,
        victory: false,
        banned: false,
      },
      gameEight: {
        game: "Pikmin",
        hallOfGreat: 8,
        votesGiven: 2,
        victory: false,
        banned: false,
      },
      gameNine: {
        game: "Final Fantasy IX",
        hallOfGreat: 9,
        votesGiven: 11,
        victory: false,
        banned: false,
      },
      gameTen: {
        game: "Phantasy Star Online",
        hallOfGreat: 10,
        votesGiven: 8,
        victory: false,
        banned: false,
      },
      gameEleven: {
        game: "Counter-Strike",
        hallOfGreat: 11,
        votesGiven: 15,
        victory: true,
        banned: false,
      },
      gameTwelve: {
        game: "The Ultimate Doom",
        hallOfGreat: 12,
        votesGiven: 11,
        victory: true,
        banned: false,
      },
      gameThirteen: {
        game: "Bayonetta",
        hallOfGreat: 13,
        votesGiven: 9,
        victory: false,
        banned: false,
      },
    },
    allySeven: {
      nominator: "Michael Damiani",
      gameOne: {
        game: "Metal Gear Solid",
        hallOfGreat: 1,
        votesGiven: 10,
        victory: true,
        banned: false,
      },
      gameTwo: {
        game: "Super Mario 64",
        hallOfGreat: 2,
        votesGiven: 15,
        victory: true,
        banned: false,
      },
      gameThree: {
        game: "The Legend of Zelda: Ocarina of Time",
        hallOfGreat: 3,
        votesGiven: 16,
        victory: true,
        banned: false,
      },
      gameFour: {
        game: "Skyrim",
        hallOfGreat: 4,
        votesGiven: 0,
        victory: false,
        banned: true,
      },
      gameFive: {
        game: "Shadow of the Colossus",
        hallOfGreat: 5,
        votesGiven: 1,
        victory: false,
        banned: false,
      },
      gameSix: {
        game: "Metroid Prime",
        hallOfGreat: 6,
        votesGiven: 19,
        victory: true,
        banned: false,
      },
      gameSeven: {
        game: "Super Mario RPG",
        hallOfGreat: 7,
        votesGiven: 2,
        victory: false,
        banned: false,
      },
      gameEight: {
        game: "FTL: Faster Than Light",
        hallOfGreat: 8,
        votesGiven: 0,
        victory: false,
        banned: true,
      },
      gameNine: {
        game: "The Legend of Zelda: A Link to the Past",
        hallOfGreat: 9,
        votesGiven: 13,
        victory: true,
        banned: false,
      },
      gameTen: {
        game: "Bioshock",
        hallOfGreat: 10,
        votesGiven: 6,
        victory: false,
        banned: false,
      },
      gameEleven: {
        game: "Teenage Mutant Ninja Turtles: Turtles in Time",
        hallOfGreat: 12,
        votesGiven: 3,
        victory: false,
        banned: false,
      },
      gameTwelve: {
        game: "Metal Gear Rising: Revengeance",
        hallOfGreat: 13,
        votesGiven: 2,
        victory: false,
        banned: false,
      },
    },
    allyEight: {
      nominator: "Ian Hinck",
      gameOne: {
        game: "Bloodborne",
        hallOfGreat: 1,
        votesGiven: 3,
        victory: false,
        banned: false,
      },
      gameTwo: {
        game: "Castlevania: Symphony of the Night",
        hallOfGreat: 2,
        votesGiven: 12,
        victory: false,
        banned: false,
      },
      gameThree: {
        game: "Castlevania: Symphony of the Night",
        hallOfGreat: 3,
        votesGiven: 11,
        victory: true,
        banned: false,
      },
      gameFour: {
        game: "Myst",
        hallOfGreat: 4,
        votesGiven: 2,
        victory: false,
        banned: false,
      },
      gameFive: {
        game: "Dungeons & Dragons",
        hallOfGreat: 5,
        votesGiven: 0,
        victory: false,
        banned: true,
      },
      gameSix: {
        game: "Silent Hill 2",
        hallOfGreat: 6,
        votesGiven: 8,
        victory: false,
        banned: false,
      },
      gameSeven: {
        game: "Silent Hill 2",
        hallOfGreat: 7,
        votesGiven: 3,
        victory: false,
        banned: false,
      },
      gameEight: {
        game: "Bloodborne",
        hallOfGreat: 8,
        votesGiven: 13,
        victory: true,
        banned: false,
      },
      gameNine: {
        game: "Dark Souls Remastered",
        hallOfGreat: 9,
        votesGiven: 0,
        victory: false,
        banned: false,
      },
      gameTen: {
        game: "Final Fantasy VII",
        hallOfGreat: 10,
        votesGiven: 1,
        victory: false,
        banned: false,
      },
      gameEleven: {
        game: "Metal Gear Solid 3: Snake Eater",
        hallOfGreat: 11,
        votesGiven: 2,
        victory: false,
        banned: false,
      },
      gameTwelve: {
        game: "Silent Hill 2",
        hallOfGreat: 12,
        votesGiven: 3,
        victory: false,
        banned: false,
      },
      gameThirteen: {
        game: "The Stanley Parable",
        hallOfGreat: 13,
        votesGiven: 1,
        victory: false,
        banned: false,
      },
    },
    allyNine: {
      nominator: "Kyle Bosman",
      gameOne: {
        game: "Mega Man Legends",
        hallOfGreat: 1,
        votesGiven: 1,
        victory: false,
        banned: false,
      },
      gameTwo: {
        game: "The Legend of Zelda: Links Awakening DX",
        hallOfGreat: 2,
        votesGiven: 5,
        victory: false,
        banned: false,
      },
      gameThree: {
        game: "Final Fantasy IX",
        hallOfGreat: 3,
        votesGiven: 9,
        victory: false,
        banned: false,
      },
      gameFour: {
        game: "Pokemon Red & Blue",
        hallOfGreat: 4,
        votesGiven: 8,
        victory: true,
        banned: false,
      },
      gameFive: {
        game: "Mega Man Legends",
        hallOfGreat: 5,
        votesGiven: 1,
        victory: false,
        banned: false,
      },
      gameSix: {
        game: "Mega Man Legends",
        hallOfGreat: 6,
        votesGiven: 1,
        victory: false,
        banned: false,
      },
      gameSeven: {
        game: "Tetris",
        hallOfGreat: 7,
        votesGiven: 13,
        victory: true,
        banned: false,
      },
      gameEight: {
        game: "The Legend of Zelda: Links Awakening DX",
        hallOfGreat: 8,
        votesGiven: 8,
        victory: false,
        banned: false,
      },
      gameNine: {
        game: "Super Mario Bros. 3",
        hallOfGreat: 9,
        votesGiven: 12,
        victory: true,
        banned: false,
      },
      gameTen: {
        game: "Halo: Combat Evolved",
        hallOfGreat: 10,
        votesGiven: 6,
        victory: false,
        banned: false,
      },
      gameEleven: {
        game: "Dungeons & Dragons",
        hallOfGreat: 11,
        votesGiven: 0,
        victory: false,
        banned: true,
      },
      gameTwelve: {
        game: "Mega Man Legends",
        hallOfGreat: 12,
        votesGiven: 5,
        victory: false,
        banned: false,
      },
    },
  },
];

db.Nominations.deleteMany({})
  .then(() => db.Nominations.collection.insertMany(nominationSeed))
  .then((data) => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });

db.Winners.deleteMany({})
  .then(() => db.Winners.collection.insertMany(winnerSeed))
  .then((data) => {
    console.log('DATA', data);
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
