const mongoose = require("mongoose");
const db = require("../models");

// This file empties the database and inserts new users and snips.
mongoose.connect(
  process.env.MONGODB_URI || "mongodb://localhost/hallOfGreatsDB",
  {
    useNewUrlParser: true,
    useFindAndModify: false,
    useUnifiedTopology: true,
  }
);

const allySeed = [
  {
    ally: "Brandon Jones",
    victories: 3,
  },
  {
    ally: "Don Casanova",
    victories: 0,
  },
  {
    ally: "Ben Moore",
    victories: 4,
  },
  {
    ally: "Brad Ellis",
    victories: 5,
  },
  {
    ally: "Michael Huber",
    victories: 2,
  },
  {
    ally: "Michael Damiani",
    victories: 5,
  },
  {
    ally: "Daniel Bloodworth",
    victories: 3,
  },
  {
    ally: "Ian Hinck",
    victories: 2,
  },
  {
    ally: "Kyle Bosman",
    victories: 3,
  },
];

const gameSeed = [
  {
    games: [
      {
        ally: "Michael Damiani",
        game: "Metal Gear Solid",
        hallOfGreat: 1,
        image: "../images/metal_gear_solid.jpg",
        description:
          "You are Snake, a government agent on a mission to regain control of a secret nuclear weapons base from terrorist hands. Lightly armed and facing an army of foes, Snake must avoid firefights in order to survive. If Snake can locate them he can utilize advanced hardware, ranging from silenced pistols to ground-to-air missiles. Enemies react to sight and sound - so stay quiet and stay in the shadows. State-of-the-art graphics: textures, transparencies, models and explosions. Taut, gripping story with multiple endings - a truly cinematic experience.",
        genre: "Action Adventure",
        year: 1998,
        platforms: "Playstation One",
        metacritic: 94,
        votes: 10,
        victory: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Daniel Bloodworth",
        game: "Super Metroid",
        hallOfGreat: 1,
        image: "../images/super_metroid.jpg",
        description:
          "Super Metroid is an 2D, side-scrolling action-adventure game, which primarily takes place on the fictional planet Zebes—a large, open-ended world with areas connected by doors and elevators. The player controls Samus Aran as she searches the planet for a Metroid that was stolen by Ridley, the leader of the Space Pirates.",
        genre: "Metroidvania",
        year: 1994,
        platforms: "Super NES",
        metacritic: 0,
        votes: 9,
        victory: true,
        wonByPatreonVote: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Ben Moore",
        game: "Super Street Fighter II Turbo",
        hallOfGreat: 1,
        votes: 9,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Ian Hinck",
        game: "Bloodborne",
        hallOfGreat: 1,
        votes: 3,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Don Casanova",
        game: "Assassin's Creed IV: Black Flag",
        hallOfGreat: 1,
        votes: 2,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Brad Ellis",
        game: "Dark Souls",
        hallOfGreat: 1,
        votes: 1,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Brandon Jones",
        game: "GoldenEye 007",
        hallOfGreat: 1,
        votes: 1,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Kyle Bosman",
        game: "Mega Man Legends",
        hallOfGreat: 1,
        votes: 1,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Michael Huber",
        game: "Resident Evil Remake",
        hallOfGreat: 1,
        votes: 0,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Brad Ellis & Michael Damiani",
        game: "Super Mario 64",
        hallOfGreat: 2,
        image: "../images/super_mario_64.jpg",
        description:
          "Mario is super in a whole new way! Combining the finest 3-D graphics ever developed for a video game and an explosive sound track, Super Mario 64 becomes a new standard for video games. It's packed with bruising battles, daunting obstacle courses and underwater adventures. Retrieve the Power Stars from their hidden locations and confront your arch nemesis - Bowser, King of the Koopas!",
        genre: "Platformer",
        year: 1996,
        platforms: "Nintendo 64",
        metacritic: 94,
        votes: 15,
        victory: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Daniel Bloodworth",
        game: "Street Fighter II",
        hallOfGreat: 2,
        image: "../images/street_fighter_two.jpg",
        description:
          "A sequel to Street Fighter, Street Fighter II improved upon the many concepts introduced in the first game, including the use of command-based special moves and a six-button configuration, while offering players a selection of multiple playable characters, each with their own unique fighting style and special moves.",
        genre: "Fighting",
        year: 1992,
        platforms: "Arcade & Super NES",
        metacritic: 0,
        nominatedBy: "Daniel Bloodworth",
        votes: 14,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Ian Hinck",
        game: "Castlevania: Symphony of the Night",
        hallOfGreat: 2,
        votes: 12,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Michael Huber",
        game: "Dragon Quest VIII: Journey of the Cursed King",
        hallOfGreat: 2,
        votes: 5,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Kyle Bosman",
        game: "The Legend of Zelda: Link's Awakening DX",
        hallOfGreate: 2,
        votes: 5,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Brandon Jones",
        game: "World of Warcraft",
        hallOfGreat: 2,
        votes: 1,
        victory: false,
        banned: true,
      },
    ],
    games: [
      {
        ally: "Don Casanova",
        game: "Sim City 4",
        hallOfGreat: 2,
        votes: 1,
        victory: false,
        banned: true,
      },
    ],
    games: [
      {
        ally: "Ben Moore",
        game: "Valkyria Chronicles",
        hallOfGreat: 2,
        votes: 1,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Michael Damiani",
        game: "The Legend of Zelda: Ocarina of Time",
        image: "../images/ocarina_of_time.jpg",
        hallOfGreat: 3,
        description:
          "The Legend of Zelda: Ocarina of Time reveals the genesis of the fantasy land of Hyrule, the origin of the Triforce, and the tale of the first exploits of Princess Zelda and the heroic adventurer Link. Vibrant, real-time 3-D graphics transport you into the fantasy world of Hyrule. Your quest takes you through dense forests and across wind-whipped deserts. Swim raging rivers, climb treacherous mountains, dash on horseback across rolling hills, and delve into dungeons full of creatures that fight to the finish to put an end to your adventures. With immersive graphics, a sweeping story line, swashbuckling adventure, mind-bending puzzles, and a touch of humor, The Legend of Zelda: Ocarina of Time is one of Nintendo's most epic challenges ever.",
        genre: "Adventure",
        year: 1998,
        platforms: "Nintendo 64",
        metacritic: 0,
        votes: 16,
        victory: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Ian Hinck",
        game: "Castlevania: Symphony of the Night",
        hallOfGreat: 3,
        image: "../images/symphony_of_the_night.jpg",
        description:
          "As a descendant of Dracula, you must end the vampire bloodline. Can you rid the world of this unspeakable terror? Uncover the mystery of Castlevania and challenge an adventure as legendary as its name. Over 140 different enemies, bosses, and ghastly creatures. Awesome magical spells - transform into a bat, a wolf, or etheral mist. Hidden weapons, secrets, and characters...the largest Castlevania ever!",
        genre: "Metroidvania",
        year: 1997,
        platforms: "Playstation One",
        metacritic: 93,
        votes: 11,
        victory: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Kyle Bosman",
        game: "Final Fantasy IX",
        hallOfGreat: 3,
        votes: 9,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Brandon Jones",
        game: "Half-Life 2",
        hallOfGreat: 3,
        votes: 5,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Daniel Bloodworth",
        game: "Portal",
        hallOfGreat: 3,
        votes: 4,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Michael Huber",
        game: "The Last of Us",
        hallOfGreat: 3,
        votes: 4,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Ben Moore",
        game: "Xenoblade Chronicles",
        hallOfGreat: 2,
        votes: 3,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Don Casanova",
        game: "Jurassic Park: Operation Genesis",
        hallOfGreat: 3,
        votes: 2,
        victory: false,
        banned: true,
      },
    ],
    games: [
      {
        ally: "Brad Ellis",
        game: "Doom (2016)",
        hallOfGreat: 3,
        votes: 0,
        victory: false,
        banned: true,
      },
    ],
    games: [
      {
        ally: "Brad Ellis",
        game: "Chrono Trigger",
        hallOfGreat: 4,
        image: "../images/chrono_trigger.jpg",
        description:
          "When a newly developed teleportation device malfunctions at the Millennial Fair, young Crono must travel through time to rescue his unfortunate companion from an intricate web of past and present perils. The swashbuckling adventure that ensues soon unveils an evil force set to destroy the world, triggering Crono's race against time to change the course of history and bring about a brighter future.",
        genre: "Role-Playing Game",
        year: 1995,
        platforms: "Super NES",
        metacritic: 96,
        votes: 21,
        victory: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Kyle Bosman",
        game: "Pokemon Red & Blue",
        hallOfGreat: 4,
        image: "../images/pokemon_red.jpg",
        description:
          "You've finally been granted your Pokémon Trainer's license. Now, it's time to head out to become the world's greatest Pokémon Trainer. It's going to take all you've got to collect 150 Pokémon in this enormous world. Catch and train monsters like the shockingly-cute Pikachu. Face off against Blastoise's torrential water cannons. Stand strong when facing Pidgeot's stormy Gust. Trade with friends and watch your Pokémon evolve. Important—no single Pokémon can win at all. Can you develop the ultimate Pokémon strategy to defeat the eight Gym Leaders and become the greatest Pokémon Master of all time?",
        genre: "Role-Playing Game",
        year: 1998,
        platforms: "Gameboy",
        metacritic: 88,
        votes: 8,
        victory: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Ben Moore",
        game: "Mega Man X",
        hallOfGreat: 4,
        votes: 7,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Brandon Jones",
        game: "Grand Theft Auto III",
        hallOfGreat: 4,
        votes: 7,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Michael Huber",
        game: "Streets of Rage 2",
        hallOfGreat: 4,
        votes: 4,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Don Casanova",
        game: "Super Mario Maker",
        hallOfGreat: 4,
        votes: 3,
        victory: false,
        banned: true,
      },
    ],
    games: [
      {
        ally: "Daniel Bloodworth",
        game: "Journey",
        hallOfGreat: 4,
        votes: 2,
        victory: false,
        banned: true,
      },
    ],
    games: [
      {
        ally: "Ian Hinck",
        game: "Myst",
        hallOfGreat: 4,
        votes: 2,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Michael Damiani",
        game: "Skyrim",
        hallOfGreat: 4,
        votes: 0,
        victory: false,
        banned: true,
      },
    ],
    games: [
      {
        ally: "Brad Ellis",
        game: "Resident Evil 4",
        hallOfGreat: 5,
        image: "../images/resident_evil_four.jpg",
        description:
          "Resident Evil 4 marks a new chapter in the Resident Evil series. You'll rejoin Leon S. Kennedy six years after his first mission as a rookie cop from Resident Evil 2. Now a US agent, Leon is on a top secret mission to investigate the disappearance of the president's daughter. As Leon, you must make your way to a mysterious location in Europe, where new enemies await. Take them down by using enhanced aim-and-shoot features and a new action button.",
        genre: "Survival Horror",
        year: 2005,
        platforms: "Nintendo Gamecube",
        metacritic: 96,
        votes: 13,
        victory: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Ben Moore",
        game: "Resident Evil Remake",
        hallOfGreat: 5,
        image: "../images/resident_evil_remake.jpg",
        description:
          "Raccoon City has been completely overrun by mutant beasts and bloodthirsty zombies. You are a member of S.T.A.R.S.--a rescue squad sent into the community to investigate the ominous mansion at the core of the disaster. Take the role of operative Jill Valentine or Chris Redfield and uncover the secrets behind a radical, genetic research facility. With an array of weapons to master and horrors around every corner, the ultimate test may be just to make it out alive.",
        genre: "Survival Horror",
        year: 2002,
        platforms: "Nintendo Gamecube",
        metacritic: 91,
        votes: 11,
        victory: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Michael Huber",
        game: "The Witcher III: Wild Hunt",
        hallOfGreat: 5,
        votes: 9,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Daniel Bloodworth",
        game: "Dark Souls",
        hallOfGreat: 5,
        votes: 7,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Don Casanova",
        game: "Pandemonium",
        hallOfGreat: 5,
        votes: 4,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Brandon Joens",
        game: "Pong",
        hallOfGreat: 5,
        votes: 2,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Michael Damiani",
        game: "Shadow of the Colossus (2018)",
        hallOfGreat: 5,
        votes: 1,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Kyle Bosman",
        game: "Mega Man Legends",
        hallOfGreat: 5,
        votes: 1,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Ian Hinck",
        game: "Dungeons & Dragons",
        hallOfGreat: 5,
        votes: 0,
        victory: false,
        banned: true,
      },
    ],
    games: [
      {
        ally: "Michael Damiani",
        game: "Metroid Prime",
        hallOfGreat: 6,
        image: "../images/metroid_prime.jpg",
        description:
          "Samus returns in a new mission to unravel the mystery behind the ruined walls scattered across Tallon IV. In Metroid Prime, you'll play the role of this bounty hunter and view the world through her visor, which displays information ranging from current energy levels to ammunition. Equipped with a Power Beam and Gravity Suit, you must shoot locked switches, solve puzzles, and eliminate enemies. It's up to you to explore the world and recover more power-ups and weapons, which gradually open more gameplay areas.",
        genre: "Metroidvania",
        year: 2002,
        platforms: "Nintendo Gamecube",
        metacritic: 97,
        votes: 19,
        victory: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Ben Moore",
        game: "Paper Mario & The Thousand-Year Door",
        hallOfGreat: 6,
        image: "../images/paper_mario_thousand.jpg",
        description:
          "Time passes, the pages turn… and a new chapter unfolds in an unfamiliar land! Get ready for a two-dimensional role-playing adventure for the ages as Mario returns to paper form to discover a mystery that sleeps behind an ancient, legendary portal called the Thousand-Year Door. The quest is long, the dangers many, and this time, Mario will have to make full use of his papery qualities just to survive.",
        genre: "Role-Playing Game",
        year: 2004,
        platforms: "Nintendo Gamecube",
        metacritic: 87,
        votes: 12,
        victory: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Ian Hinck",
        game: "Silent Hill 2",
        hallOfGreat: 6,
        votes: 8,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Daniel Bloodworth",
        game: "Dragon Quest VIII: Journey of the Cursed King",
        hallOfGreat: 6,
        votes: 7,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Don Casanova",
        game: "Sim City 4",
        hallOfGreat: 6,
        votes: 3,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Brad Ellis",
        game: "Donkey Kong Country: Tropical Freeze",
        hallOfGreat: 6,
        votes: 2,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Brandon Jones",
        game: "Grand Theft Auto V",
        hallOfGreat: 6,
        votes: 1,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Kyle Bosman",
        game: "Mega Man Legends",
        hallOfGreat: 6,
        votes: 1,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Michael Huber",
        game: "Time Crisis 2",
        hallOfGreat: 6,
        votes: 1,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Brandon Jones",
        game: "Final Fantasy VI",
        hallOfGreat: 7,
        image: "../images/ff_six.jp",
        description:
          "Part of the Final Fantasy turn-based Japanese RPG franchise, Final Fantasy VI follows an ensemble cast of characters as they attempt to save the their steampunk/fantasy land from the repercussions of the otherworldly campaigns of Emperor Gestahl and his court jester/general Kefka, while trying to resolve their personal issues together and find meaning in their own existence through their tumultuous journey.",
        genre: "Role-Playing Game",
        year: 1994,
        platforms: "Super NES",
        metacritic: 94,
        votes: 13,
        victory: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Kyle Bosman",
        game: "Tetris",
        hallOfGreat: 7,
        image: "../images/tetris.jpg",
        description:
          "Tetris is a puzzle video game for the Game Boy released in 1989. It is a portable version of Alexey Pajitnov's original Tetris and it was bundled in the North American and European releases of the Game Boy itself. It was the first game compatible with the Game Link Cable, a pack-in accessory that allowed two Game Boys to link together for multiplayer purposes.",
        genre: "Puzzle",
        year: 1989,
        platforms: "Gameboy",
        metacritic: 0,
        votes: 13,
        victory: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Brad Ellis",
        game: "Bloodborne",
        hallOfGreat: 7,
        votes: 9,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Don Casanova",
        game: "Mortal kombat (2011)",
        hallOfGreat: 7,
        votes: 8,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Ben Moore",
        game: "Halo: Combat Evolved",
        hallOfGreat: 7,
        votes: 3,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Michael Huber",
        game: "Batman: Arkham City",
        hallOfGreat: 7,
        votes: 3,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Ian Hinck",
        game: "Silent Hill 2",
        hallOfGreat: 7,
        votes: 3,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Michael Damiani",
        game: "Super Mario RPG",
        hallOfGreat: 7,
        votes: 2,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Daniel Bloodworth",
        game: "Ms. Pac-Man",
        hallOfGreat: 7,
        votes: 0,
        victory: false,
        banned: true,
      },
    ],
    games: [
      {
        ally: "Ian Hinck",
        game: "Bloodborne",
        hallOfGreat: 8,
        image: "../images/bloodborne.jpg",
        description:
          "Bloodborne is an action RPG in which you hunt for answers in the ancient city of Yharnam, now cursed with a strange endemic illness spreading through the streets like a disease. Peril, death and madness infest this dark world, and you're tasked with uncovering its darkest secrets which will be necessary for you to survive. Armed with a singular arsenal of weaponry, including guns and saw cleavers, you'll require wits, strategy and reflexes to dispatch the agile and intelligent enemies that guard the city's underbelly. You will utility holy chalices to access an array of vast underground ruins, chock full of traps, beasts, and rewards, to explore and conquer on your own or with other people.",
        genre: "Action Role-Playing Game",
        year: 2015,
        platforms: "Playstation 4",
        metacritic: 92,
        votes: 13,
        victory: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Brandon Jones",
        game: "Portal",
        hallOfGreat: 8,
        image: "../images/portal.jpg",
        description:
          "Set in the mysterious Aperture Science Laboratories, Portal has been called one of the most innovative new games on the horizon and offers gamers hours of unique gameplay. The game is designed to change the way players approach, manipulate, and surmise the possibilities in a given environment; similar to how Half-Life 2's Gravity Gun innovated new ways to leverage an object in any given situation. Players must solve physical puzzles and challenges by opening portals to maneuvering objects, and themselves, through space. ",
        genre: "Puzzle",
        year: 2007,
        platforms: "PC",
        metacritic: 90,
        votes: 11,
        victory: true,
        wonByPatreonVote: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Brad Ellis",
        game: "God of War (2018)",
        hallOfGreat: 8,
        votes: 11,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Kyle Bosman",
        game: "The Legend of Zelda: Link's Awakening",
        hallOfGreat: 8,
        votes: 8,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Don Casanova",
        game: "Trials Fusion",
        hallOfGreat: 8,
        votes: 6,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Michael Huber",
        game: "The Last of Us",
        hallOfGreat: 8,
        votes: 3,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Ben Moore",
        game: "Pikmin",
        hallOfGreat: 8,
        votes: 2,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Daniel Bloodworth",
        game: "Deus Ex",
        hallOfGreat: 8,
        votes: 0,
        victory: false,
        banned: true,
      },
    ],
    games: [
      {
        ally: "Michael Damiani",
        game: "FTL: Faster Than Light",
        hallOfGreat: 8,
        votes: 0,
        victory: false,
        banned: true,
      },
    ],
    games: [
      {
        ally: "Michael Damiani",
        game: "The Legend of Zelda: A Link to the Past",
        hallOfGreat: 9,
        image: "../images/link_past.jpg",
        description:
          "A top-down action/adventure title in which Link, a blacksmith's nephew living in the fantastical land of Hyrule, must free the land from the evildoings of Ganon by taking up the mythical Master Sword and collecting the three Triforces in order to free the Seven Maidens, including the princess of Hyrule, Zelda, from the dungeons and castles of the Dark World.",
        genre: "Action-Adventure",
        year: 1991,
        platforms: "Super NES",
        metacritic: 92,
        votes: 13,
        victory: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Kyle Bosman",
        game: "Super Mario Bros. 3",
        hallOfGreat: 9,
        image: "../images/super_mario_bros_three.jpg",
        description:
          "Your mission is to rescue the Mushroom Kingdom monarchs who have been transformed into animals by Bowser and his mischievous offspring, and in the process save the princess kidnapped by Bowser.",
        genre: "Platformer",
        year: 1988,
        platforms: "NES",
        metacritic: 97,
        votes: 12,
        victory: true,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Ben Moore",
        game: "Final Fantasy IX",
        hallOfGreat: 8,
        votes: 11,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Brad Ellis",
        game: "The Legend of Zelda: Twilight Princess",
        hallOfGreat: 8,
        votes: 6,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Don Casanova",
        game: "WaveRace 64",
        hallOfGreat: 9,
        votes: 3,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Michael Huber",
        game: "Sekiro: Shadows Die Twice",
        hallOfGreat: 9,
        votes: 3,
        victory: false,
        banned: false,
      },
    ],
    games: [
      {
        ally: "Brandon Jones",
        game: "GoldenEye 007",
        hallOfGreat: 9,
        votes: 0,
        victory: false,
        banned: true,
      },
    ],
    games: [
      {
        ally: "Ian Hinck",
        game: "Dark Souls: Remastered",
        hallOfGreat: 9,
        votes: 0,
        victory: false,
        banned: true,
      },
    ],

  },
];
// ally: { type: Schema.Types.ObjectId, ref: "Allies" },
// game: { type: String, required: true },
// hallOfGreat: { type: Number, required: true },
// image: { type: Buffer, contentType: String, required: false },
// description: { type: String, required: false },
// genre: { type: String, required: false },
// year: { type: Number, required: false },
// platforms: { type: String, required: false },
// metacritic: { type: Number, required: false },
// votes: { type: Number, required: false },
// victory: { type: Boolean, required: false },
// banned: { type: Boolean, required: false },
// nominatedMultiple: { type: Boolean, required: false }

// const winnnerSeed = [
//   {
//     hallOfGreatsOne: {
//       gameOne: {
//         name: "Metal Gear Solid",
//         image: "../images/metal_gear_solid.jpg",
//         description:
//           "You are Snake, a government agent on a mission to regain control of a secret nuclear weapons base from terrorist hands. Lightly armed and facing an army of foes, Snake must avoid firefights in order to survive. If Snake can locate them he can utilize advanced hardware, ranging from silenced pistols to ground-to-air missiles. Enemies react to sight and sound - so stay quiet and stay in the shadows. State-of-the-art graphics: textures, transparencies, models and explosions. Taut, gripping story with multiple endings - a truly cinematic experience.",
//         genre: "Action Adventure",
//         year: 1998,
//         platforms: "Playstation One",
//         metacritic: 94,
//         nominatedBy: "Michael Damiani",
//         votes: 10,
//       },
//       gameTwo: {
//         name: "Super Metroid",
//         image: "../images/super_metroid.jpg",
//         description:
//           "Super Metroid is an 2D, side-scrolling action-adventure game, which primarily takes place on the fictional planet Zebes—a large, open-ended world with areas connected by doors and elevators. The player controls Samus Aran as she searches the planet for a Metroid that was stolen by Ridley, the leader of the Space Pirates.",
//         genre: "Metroidvania",
//         year: 1994,
//         platforms: "Super NES",
//         metacritic: "-",
//         nominatedBy: "Daniel Bloodworth",
//         votes: 9,
//       },
//     },
//     hallOfGreatsTwo: {
//       gameOne: {
//         name: "Super Mario 64",
//         image: "../images/super_mario_64.jpg",
//         description:
//           "Mario is super in a whole new way! Combining the finest 3-D graphics ever developed for a video game and an explosive sound track, Super Mario 64 becomes a new standard for video games. It's packed with bruising battles, daunting obstacle courses and underwater adventures. Retrieve the Power Stars from their hidden locations and confront your arch nemesis - Bowser, King of the Koopas!",
//         genre: "Platformer",
//         year: 1996,
//         platforms: "Nintendo 64",
//         metacritic: 94,
//         nominatedBy: "Michael Damiani & Brad Ellis",
//         votes: 15,
//       },
//       gameTwo: {
//         name: "Street Fighter II",
//         image: "../images/street_fighter_two.jpg",
//         description:
//           "A sequel to Street Fighter, Street Fighter II improved upon the many concepts introduced in the first game, including the use of command-based special moves and a six-button configuration, while offering players a selection of multiple playable characters, each with their own unique fighting style and special moves.",
//         genre: "Fighting",
//         year: "1992",
//         platforms: "Arcade & Super NES",
//         metacritic: "-",
//         nominatedBy: "Daniel Bloodworth",
//         votes: 14,
//       },
//     },
//     hallOfGreatsThree: {
//       gameOne: {
ç; //       },
//       gameTwo: {
//         name: "Castlevania: Symphony of the Night",
//         image: "../images/symphony_of_the_night.jpg",
//         description:
//           "As a descendant of Dracula, you must end the vampire bloodline. Can you rid the world of this unspeakable terror? Uncover the mystery of Castlevania and challenge an adventure as legendary as its name. Over 140 different enemies, bosses, and ghastly creatures. Awesome magical spells - transform into a bat, a wolf, or etheral mist. Hidden weapons, secrets, and characters...the largest Castlevania ever!",
//         genre: "Metroidvania",
//         year: 1997,
//         platforms: "Playstation One",
//         metacritic: 93,
//         nominatedBy: "Ian Hinck",
//         votes: 11,
//       },
//     },
//     hallOfGreatsFour: {
//       gameOne: {
//         name: "Chrono Trigger",
//         image: "../images/chrono_trigger.jpg",
//         description:
//           "When a newly developed teleportation device malfunctions at the Millennial Fair, young Crono must travel through time to rescue his unfortunate companion from an intricate web of past and present perils. The swashbuckling adventure that ensues soon unveils an evil force set to destroy the world, triggering Crono's race against time to change the course of history and bring about a brighter future.",
//         genre: "Role-Playing Game",
//         year: 1995,
//         platforms: "Super NES",
//         metacritic: 96,
//         nominatedBy: "Brad Ellis",
//         votes: 21,
//       },
//       gameTwo: {
//         name: "Pokemon Red & Blue",
//         image: "",
//         description:
//           "You've finally been granted your Pokémon Trainer's license. Now, it's time to head out to become the world's greatest Pokémon Trainer. It's going to take all you've got to collect 150 Pokémon in this enormous world. Catch and train monsters like the shockingly-cute Pikachu. Face off against Blastoise's torrential water cannons. Stand strong when facing Pidgeot's stormy Gust. Trade with friends and watch your Pokémon evolve. Important—no single Pokémon can win at all. Can you develop the ultimate Pokémon strategy to defeat the eight Gym Leaders and become the greatest Pokémon Master of all time?",
//         genre: "Role-Playing Game",
//         year: 1998,
//         platforms: "Gameboy",
//         metacritic: 88,
//         nominatedBy: "Kyle Bosman",
//         votes: 8,
//       },
//     },
//     hallOfGreatsFive: {
//       gameOne: {
//         name: "Resident Evil 4",
//         image: "../images/resident_evil_four.jpg",
//         description:
//           "Resident Evil 4 marks a new chapter in the Resident Evil series. You'll rejoin Leon S. Kennedy six years after his first mission as a rookie cop from Resident Evil 2. Now a US agent, Leon is on a top secret mission to investigate the disappearance of the president's daughter. As Leon, you must make your way to a mysterious location in Europe, where new enemies await. Take them down by using enhanced aim-and-shoot features and a new action button.",
//         genre: "Survival Horror",
//         year: 2005,
//         platforms: "Nintendo Gamecube",
//         metacritic: 96,
//         nominatedBy: "Brad Ellis",
//         votes: 13,
//       },
//       gameTwo: {
//         name: "Resident Evil Remake",
//         image: "../images/resident_evil_remake.jpg",
//         description:
//           "Raccoon City has been completely overrun by mutant beasts and bloodthirsty zombies. You are a member of S.T.A.R.S.--a rescue squad sent into the community to investigate the ominous mansion at the core of the disaster. Take the role of operative Jill Valentine or Chris Redfield and uncover the secrets behind a radical, genetic research facility. With an array of weapons to master and horrors around every corner, the ultimate test may be just to make it out alive.",
//         genre: "Survival Horror",
//         year: 2002,
//         platforms: "Nintendo Gamecube",
//         metacritic: 91,
//         nominatedBy: "Ben Moore",
//         votes: 11,
//       },
//     },
//     hallOfGreatsSix: {
//       gameOne: {
//         name: "Metroid Prime",
//         image: "../images/metroid_prime.jpg",
//         description:
//           "Samus returns in a new mission to unravel the mystery behind the ruined walls scattered across Tallon IV. In Metroid Prime, you'll play the role of this bounty hunter and view the world through her visor, which displays information ranging from current energy levels to ammunition. Equipped with a Power Beam and Gravity Suit, you must shoot locked switches, solve puzzles, and eliminate enemies. It's up to you to explore the world and recover more power-ups and weapons, which gradually open more gameplay areas.",
//         genre: "Metroidvania",
//         year: 2002,
//         platforms: "Nintendo Gamecube",
//         metacritic: 97,
//         nominatedBy: "Michael Damiani",
//         votes: 19,
//       },
//       gameTwo: {
//         name: "Paper Mario & The Thousand-Year Door",
//         image: "../images/paper_mario_thousand.jpg",
//         description:
//           "Time passes, the pages turn… and a new chapter unfolds in an unfamiliar land! Get ready for a two-dimensional role-playing adventure for the ages as Mario returns to paper form to discover a mystery that sleeps behind an ancient, legendary portal called the Thousand-Year Door. The quest is long, the dangers many, and this time, Mario will have to make full use of his papery qualities just to survive.",
//         genre: "Role-Playing Game",
//         year: 2004,
//         platforms: "Nintendo Gamecube",
//         metacritic: 87,
//         nominatedBy: "Ben Moore",
//         votes: 12,
//       },
//     },
//     hallOfGreatsSeven: {
//       gameOne: {
//         name: "Final Fantasy VI",
//         image: "../images/ff_six.jp",
//         description:
//           "Part of the Final Fantasy turn-based Japanese RPG franchise, Final Fantasy VI follows an ensemble cast of characters as they attempt to save the their steampunk/fantasy land from the repercussions of the otherworldly campaigns of Emperor Gestahl and his court jester/general Kefka, while trying to resolve their personal issues together and find meaning in their own existence through their tumultuous journey.",
//         genre: "Role-Playing Game",
//         year: 1994,
//         platforms: "Super NES",
//         metacritic: 94,
//         nominatedBy: "Brandon Jones",
//         votes: 13,
//       },
//       gameTwo: {
//         name: "Tetris",
//         image: "../images/tetris.jpg",
//         description:
//           "Tetris is a puzzle video game for the Game Boy released in 1989. It is a portable version of Alexey Pajitnov's original Tetris and it was bundled in the North American and European releases of the Game Boy itself. It was the first game compatible with the Game Link Cable, a pack-in accessory that allowed two Game Boys to link together for multiplayer purposes.",
//         genre: "Puzzle",
//         year: 1989,
//         platforms: "",
//         metacritic: "-",
//         nominatedBy: "Kyle Bosman",
//         votes: 13,
//       },
//     },
//     hallOfGreatsEight: {
//       gameOne: {
//         name: "Bloodborne",
//         image: "../images/bloodborne.jpg",
//         description:
//           "Bloodborne is an action RPG in which you hunt for answers in the ancient city of Yharnam, now cursed with a strange endemic illness spreading through the streets like a disease. Peril, death and madness infest this dark world, and you're tasked with uncovering its darkest secrets which will be necessary for you to survive. Armed with a singular arsenal of weaponry, including guns and saw cleavers, you'll require wits, strategy and reflexes to dispatch the agile and intelligent enemies that guard the city's underbelly. You will utility holy chalices to access an array of vast underground ruins, chock full of traps, beasts, and rewards, to explore and conquer on your own or with other people.",
//         genre: "Action Role-Playing Game",
//         year: 2015,
//         platforms: "Playstation 4",
//         metacritic: 92,
//         nominatedBy: "Ian Hinck",
//         votes: 13,
//       },
//       gameTwo: {
//         name: "Portal",
//         image: "../images/portal.jpg",
//         description:
//           "Set in the mysterious Aperture Science Laboratories, Portal has been called one of the most innovative new games on the horizon and offers gamers hours of unique gameplay. The game is designed to change the way players approach, manipulate, and surmise the possibilities in a given environment; similar to how Half-Life 2's Gravity Gun innovated new ways to leverage an object in any given situation. Players must solve physical puzzles and challenges by opening portals to maneuvering objects, and themselves, through space. ",
//         genre: "Puzzle",
//         year: 2007,
//         platforms: "PC",
//         metacritic: 90,
//         nominatedBy: "Brandon Jones",
//         votes: 11,
//       },
//     },
//     hallOfGreatsNine: {
//       gameOne: {
//         name: "The Legend of Zelda: A Link to the Past",
//         image: "../images/link_past.jpg",
//         description:
//           "A top-down action/adventure title in which Link, a blacksmith's nephew living in the fantastical land of Hyrule, must free the land from the evildoings of Ganon by taking up the mythical Master Sword and collecting the three Triforces in order to free the Seven Maidens, including the princess of Hyrule, Zelda, from the dungeons and castles of the Dark World.",
//         genre: "Action-Adventure",
//         year: 1991,
//         platforms: "Super NES",
//         metacritic: 92,
//         nominatedBy: "Michael Damiani",
//         votes: 13,
//       },
//       gameTwo: {
//         name: "Super Mario Bros. 3",
//         image: "../images/super_mario_bros_three.jpg",
//         description:
//           "Your mission is to rescue the Mushroom Kingdom monarchs who have been transformed into animals by Bowser and his mischievous offspring, and in the process save the princess kidnapped by Bowser.",
//         genre: "Platformer",
//         year: 1988,
//         platforms: "NES",
//         metacritic: 97,
//         nominatedBy: "Kyle Bosman",
//         votes: 12,
//       },
//     },
//     hallOfGreatsTen: {
//       gameOne: {
//         name: "The Last of Us",
//         image: "../images/the_last_of_us.jpg",
//         description:
//           "Twenty years after a pandemic radically transformed known civilization, infected humans run amuck and survivors kill one another for sustenance and weapons - literally whatever they can get their hands on. Joel, a salty survivor, is hired to smuggle a fourteen-year-old girl, Ellie, out of a rough military quarantine, but what begins as a simple job quickly turns into a brutal journey across the country.",
//         genre: "Action-Adventure",
//         year: 2013,
//         platforms: "Playstation 3",
//         metacritic: 95,
//         nominatedBy: "Michael Huber",
//         votes: 8,
//       },
//       gameTwo: {
//         name: "The Witcher III: The Wild Hunt",
//         image: "../images/the_witcher_three.jpg",
//         description:
//           "With the Empire attacking the Kingdoms of the North and the Wild Hunt, a cavalcade of ghastly riders, breathing down your neck, the only way to survive is to fight back. As Geralt of Rivia, a master swordsman and monster hunter, leave none of your enemies standing. Explore a gigantic open world, slay beasts and decide the fates of whole communities with your actions, all in a genuine next generation format.",
//         genre: "Action Role-Playing Game",
//         year: 2015,
//         platforms: "Playstation 4, Xbox One, PC",
//         metacritic: 92,
//         nominatedBy: "Daniel Bloodworth",
//         votes: 8,
//       },
//     },
//     hallOfGreatsEleven: {
//       gameOne: {
//         name: "Counter-Strike",
//         image: "../images/counter_strike.jpg",
//         description:
//           "Play the world's number 1 online action game. Engage in an incredibly realistic brand of terrorist warfare in this wildly popular team-based game. Ally with teammates to complete strategic missions. Take out enemy sites. Rescue hostages. Your role affects your team's success. Your team's success affects your role.",
//         genre: "First-Person Shooter",
//         year: 2000,
//         platforms: "PC",
//         metacritic: 88,
//         nominatedBy: "Ben Moore",
//         votes: 12,
//       },
//       gameTwo: {
//         name: "Final Fantasy VII",
//         image: "../images/ff_seven.jpg",
//         description:
//           "What begins as a rebellion against an evil corporation becomes much more. And what erupts goes beyond imagination. With vivid landscapes, lush 3D animation and environments, Square Soft's multi-million dollar masterpiece is like nothing ever seen before.",
//         genre: "Role-Playing Game",
//         year: 1997,
//         platforms: "Playstation One",
//         metacritic: 92,
//         nominatedBy: "Brad Ellis",
//         votes: 13,
//       },
//     },
//     hallOfGreatsTwelve: {
//       gameOne: {
//         name: "World of Warcraft",
//         image: "../images/world_of_warcraft.jpg",
//         description:
//           "World of Warcraft is a massively multiplayer online roleplaying game (MMORPG) set in the Warcraft universe. Players assume the roles of Warcraft heroes as they explore, adventure, and quest across a vast world. Being Massively Multiplayer, World of Warcraft allows thousands of players to interact within the same world. Whether adventuring together or fighting against each other in epic battles, players will form friendships, forge alliances, and compete with enemies for power and glory.",
//         genre: "MMO Role-Playing Game",
//         year: 2004,
//         platforms: "PC",
//         metacritic: 93,
//         nominatedBy: "Brandon Jones",
//         votes: 14,
//       },
//       gameTwo: {
//         name: "The Ultimate Doom",
//         image: "../images/ultimate_doom.jpg",
//         description:
//           "Things aren't looking too good. You'll never navigate off the planet on your own. Plus, all the heavy weapons have been taken by the assault team leaving you with only a pistol. If you only could get your hands around a plasma rifle or even a shotgun you could take a few down on your way out. Whatever killed your buddies deserves a couple of pellets in the forehead. Securing your helmet, you exit the landing pod. Hopefully you can find more substantial firepower somewhere within the station. As you walk through the main entrance of the base, you hear animal-like growls echoing through the distant corridors. They know you're here. There's no turning back now.",
//         genre: "First-Person Shooter",
//         year: 1995,
//         platforms: "PC",
//         metacritic: 91,
//         nominatedBy: "Ben Moore",
//         votes: 11,
//       },
//     },
//     hallOfGreatsThirteen: {
//       gameOne: {
//         name: "Donkey Kong Country: Tropical Freeze",
//         image: "../images/dk_tropical_freeze.jpg",
//         description:
//           "All the challenging ground-pounding, barrel-blasting, side-scrolling mine cart action from the Donkey Kong Country series is back along with a bushel of new game-play elements and features. And now, there are four playable characters! Dixie Kong is back to join the adventure as a playable character alongside Diddy Kong, and for the first time in Donkey Kong Country, bearded old hero Cranky Kong joins the adventure with his bouncy cane. Any of the three can buddy up with Donkey Kong, and each character offers a different gameplay experience. On their journey to reclaim Donkey Kong Island, Donkey Kong and his friends travel across five islands with a variety of stages that include underwater areas and frozen environments.",
//         genre: "Platformer",
//         year: 2014,
//         platforms: "Nintendo Wii U & Nintendo Switch",
//         metacritic: 86,
//         nominatedBy: "Brad Ellis",
//         votes: 14,
//       },
//       gameTwo: {
//         name: "Yakuza 0",
//         image: "../images/yakuza_zero.jpg",
//         description:
//           "Tokyo 1988. Getting rich is easy, the women are beautiful, and everyone wants in on the action. It's time to become Yakuza. The glitz, glamour, and unbridled decadence of the 80s are back in Yakuza 0! Fight like hell through Tokyo and Osaka with protagonist Kazuma Kiryu and series regular Goro Majima. Play as Kazuma Kiryu and discover how he finds himself in a world of trouble when a simple debt collection goes wrong and his mark winds up murdered. Then, step into the silver-toed shoes of Goro Majima and explore his normal life as the proprietor of a cabaret club.",
//         genre: "Action-Adventure",
//         year: 2017,
//         platforms: "Playstation 4, Xbox One, PC",
//         metacritic: 85,
//         nominatedBy: "Michael Huber",
//         votes: 12,
//       },
//     },
//   },
// ];

// const nominationSeed = [
//   {
//     allyOne: {
//       nominator: "Don Casanova",
//       gameOne: {
//         game: "Assassins Creed IV: Black Flag",
//         hallOfGreat: 1,
//         votesGiven: 2,
//         victory: false,
//         banned: false,
//       },
//       gameTwo: {
//         game: "Sim City 4",
//         hallOfGreat: 2,
//         votesGiven: 1,
//         victory: false,
//         banned: true,
//       },
//       gameThree: {
//         game: "Jurassic Park: Operations Genesis",
//         hallOfGreat: 3,
//         votesGiven: 2,
//         victory: false,
//         banned: true,
//       },
//       gameFour: {
//         game: "Super Mario Maker",
//         hallOfGreat: 4,
//         votesGiven: 3,
//         victory: false,
//         banned: true,
//       },
//       gameFive: {
//         game: "Pandemonium",
//         hallOfGreat: 5,
//         votesGiven: 4,
//         victory: false,
//         banned: false,
//       },
//       gameSix: {
//         game: "Sim City 4",
//         hallOfGreat: 6,
//         votesGiven: 3,
//         victory: false,
//         banned: false,
//       },
//       gameSeven: {
//         game: "Mortal Kombat 2011",
//         hallOfGreat: 7,
//         votesGiven: 8,
//         victory: false,
//         banned: false,
//       },
//       gameEight: {
//         game: "Trials Fusion",
//         hallOfGreat: 8,
//         votesGiven: 6,
//         victory: false,
//         banned: false,
//       },
//       gameNine: {
//         game: "Wave Race 64",
//         hallOfGreat: 9,
//         votesGiven: 3,
//         victory: false,
//         banned: false,
//       },
//       gameTen: {
//         game: "Burnout 3: Takedown",
//         hallOfGreat: 10,
//         votesGiven: 5,
//         victory: false,
//         banned: false,
//       },
//       gameEleven: {
//         game: "Aliens vs. Predator",
//         hallOfGreat: 11,
//         votesGiven: 12,
//         victory: false,
//         banned: false,
//       },
//       gameTwelve: {
//         game: "Huntdown",
//         hallOfGreat: 13,
//         votesGiven: 0,
//         victory: false,
//         banned: true,
//       },
//     },
//     allyTwo: {
//       nominator: "Brandon Jones",
//       gameOne: {
//         game: "Goldeneye 007",
//         hallOfGreat: 1,
//         votesGiven: 1,
//         victory: false,
//         banned: false,
//       },
//       gameTwo: {
//         game: "World of Warcraft",
//         hallOfGreat: 2,
//         votesGiven: 1,
//         victory: false,
//         banned: true,
//       },
//       gameThree: {
//         game: "Half-Life 2",
//         hallOfGreat: 3,
//         votesGiven: 5,
//         victory: false,
//         banned: false,
//       },
//       gameFour: {
//         game: "Grand Theft Auto III",
//         hallOfGreat: 4,
//         votesGiven: 7,
//         victory: false,
//         banned: false,
//       },
//       gameFive: {
//         game: "Pong",
//         hallOfGreat: 5,
//         votesGiven: 2,
//         victory: false,
//         banned: false,
//       },
//       gameSix: {
//         game: "Grand Theft Auto V",
//         hallOfGreat: 6,
//         votesGiven: 1,
//         victory: false,
//         banned: false,
//       },
//       gameSeven: {
//         game: "Final Fantasy VI",
//         hallOfGreat: 7,
//         votesGiven: 13,
//         victory: true,
//         banned: false,
//       },
//       gameEight: {
//         game: "Portal",
//         hallOfGreat: 8,
//         votesGiven: 11,
//         victory: true,
//         banned: false,
//       },
//       gameNine: {
//         game: "Goldeneye 007",
//         hallOfGreat: 9,
//         votesGiven: 0,
//         victory: false,
//         banned: true,
//       },
//       gameTen: {
//         game: "Plants vs. Zombies",
//         hallOfGreat: 11,
//         votesGiven: 1,
//         victory: false,
//         banned: false,
//       },
//       gameEleven: {
//         game: "World of Warcraft",
//         hallOfGreat: 12,
//         votesGiven: 14,
//         victory: true,
//         banned: false,
//       },
//       gameTwelve: {
//         game: "Journey",
//         hallOfGreat: 13,
//         votesGiven: 6,
//         victory: false,
//         banned: false,
//       },
//     },
//     allyThree: {
//       nominator: "Brad Ellis",
//       gameOne: {
//         game: "Dark Souls",
//         hallOfGreat: 1,
//         votesGiven: 1,
//         victory: false,
//         banned: false,
//       },
//       gameTwo: {
//         game: "Super Mario 64",
//         hallOfGreat: 2,
//         votesGiven: 15,
//         victory: true,
//         banned: false,
//       },
//       gameThree: {
//         game: "Doom 2016",
//         hallOfGreat: 3,
//         votesGiven: 0,
//         victory: false,
//         banned: true,
//       },
//       gameFour: {
//         game: "Chrono Trigger",
//         hallOfGreat: 4,
//         votesGiven: 21,
//         victory: true,
//         banned: false,
//       },
//       gameFive: {
//         game: "Resident Evil 4",
//         hallOfGreat: 5,
//         votesGiven: 13,
//         victory: true,
//         banned: false,
//       },
//       gameSix: {
//         game: "Donkey Kong Country: Tropical Freeze",
//         hallOfGreat: 6,
//         votesGiven: 2,
//         victory: false,
//         banned: false,
//       },
//       gameSeven: {
//         game: "Bloodborne",
//         hallOfGreat: 7,
//         votesGiven: 9,
//         victory: false,
//         banned: false,
//       },
//       gameEight: {
//         game: "God of War 2018",
//         hallOfGreat: 8,
//         votesGiven: 11,
//         victory: false,
//         banned: false,
//       },
//       gameNine: {
//         game: "The Legend of Zelda: Twilight Princess",
//         hallOfGreat: 9,
//         votesGiven: 6,
//         victory: false,
//         banned: false,
//       },
//       gameTen: {
//         game: "Final Fantasy VII",
//         hallOfGreat: 11,
//         votesGiven: 13,
//         victory: true,
//         banned: false,
//       },
//       gameEleven: {
//         game: "Shovel Knight: Treasure Trove",
//         hallOfGreat: 12,
//         votesGiven: 4,
//         victory: false,
//         banned: false,
//       },
//       gameTwelve: {
//         game: "Donkey Kong Country: Tropical Freeze",
//         hallOfGreat: 13,
//         votesGiven: 14,
//         victory: true,
//         banned: false,
//       },
//     },
//     allyFour: {
//       nominator: "Daniel Bloodworth",
//       gameOne: {
//         game: "Super Metroid",
//         hallOfGreat: 1,
//         votesGiven: 9,
//         victory: true,
//         banned: false,
//       },
//       gameTwo: {
//         game: "Street Fighter II",
//         hallOfGreat: 2,
//         votesGiven: 14,
//         victory: true,
//         banned: false,
//       },
//       gameThree: {
//         game: "Portal",
//         hallOfGreat: 3,
//         votesGiven: 4,
//         victory: false,
//         banned: false,
//       },
//       gameFour: {
//         game: "Journey",
//         hallOfGreat: 4,
//         votesGiven: 2,
//         victory: false,
//         banned: false,
//       },
//       gameFive: {
//         game: "Dark Souls",
//         hallOfGreat: 5,
//         votesGiven: 7,
//         victory: false,
//         banned: false,
//       },
//       gameSix: {
//         game: "Dragon Quest VIII",
//         hallOfGreat: 6,
//         votesGiven: 7,
//         victory: false,
//         banned: false,
//       },
//       gameSeven: {
//         game: "Ms. Pacman",
//         hallOfGreat: 7,
//         votesGiven: 0,
//         victory: false,
//         banned: true,
//       },
//       gameEight: {
//         game: "Deus Ex",
//         hallOfGreat: 8,
//         votesGiven: 0,
//         victory: false,
//         banned: true,
//       },
//       gameNine: {
//         game: "The Witcher III: The Wild Hunt",
//         hallOfGreat: 10,
//         votesGiven: 8,
//         victory: true,
//         banned: false,
//       },
//       gameTen: {
//         game: "Animal Crossing",
//         hallOfGreat: 11,
//         votesGiven: 3,
//         victory: false,
//         banned: false,
//       },
//       gameEleven: {
//         game: "Guitar Hero II",
//         hallOfGreat: 12,
//         votesGiven: 2,
//         victory: false,
//         banned: false,
//       },
//       gameTwelve: {
//         game: "Katamari Damacy",
//         hallOfGreat: 13,
//         votesGiven: 4,
//         victory: false,
//         banned: false,
//       },
//     },
//     allyFive: {
//       nominator: "Michael Huber",
//       gameOne: {
//         game: "Resident Evil Remake",
//         hallOfGreat: 1,
//         votesGiven: 0,
//         victory: false,
//         banned: false,
//       },
//       gameTwo: {
//         game: "Dragon Quest VIII",
//         hallOfGreat: 2,
//         votesGiven: 5,
//         victory: false,
//         banned: false,
//       },
//       gameThree: {
//         game: "The Last of Us",
//         hallOfGreat: 3,
//         votesGiven: 4,
//         victory: false,
//         banned: false,
//       },
//       gameFour: {
//         game: "Streets of Rage 2",
//         hallOfGreat: 4,
//         votesGiven: 4,
//         victory: false,
//         banned: false,
//       },
//       gameFive: {
//         game: "The Witcher III: The Wild Hunt",
//         hallOfGreat: 5,
//         votesGiven: 9,
//         victory: false,
//         banned: false,
//       },
//       gameSix: {
//         game: "Time Crisis 2",
//         hallOfGreat: 6,
//         votesGiven: 1,
//         victory: false,
//         banned: false,
//       },
//       gameSeven: {
//         game: "Batman: Arkham City",
//         hallOfGreat: 7,
//         votesGiven: 3,
//         victory: false,
//         banned: false,
//       },
//       gameEight: {
//         game: "The Last of Us",
//         hallOfGreat: 8,
//         votesGiven: 3,
//         victory: false,
//         banned: false,
//       },
//       gameNine: {
//         game: "Sekiro: Shadows Die Twice",
//         hallOfGreat: 9,
//         votesGiven: 3,
//         victory: false,
//         banned: false,
//       },
//       gameTen: {
//         game: "The Last of Us",
//         hallOfGreat: 10,
//         votesGiven: 8,
//         victory: true,
//         banned: false,
//       },
//       gameEleven: {
//         game: "Marvels Spider-Man",
//         hallOfGreat: 11,
//         votesGiven: 2,
//         victory: false,
//         banned: false,
//       },
//       gameTwelve: {
//         game: "Super Smash Brothers. Ultimate",
//         hallOfGreat: 12,
//         votesGiven: 6,
//         victory: false,
//         banned: false,
//       },
//       gameThirteen: {
//         game: "Yakuza 0",
//         hallOfGreat: 13,
//         votesGiven: 12,
//         victory: true,
//         banned: false,
//       },
//     },
//     allySix: {
//       nominator: "Ben Moore",
//       gameOne: {
//         game: "Street Fighter II Turbo",
//         hallOfGreat: 1,
//         votesGiven: 9,
//         victory: false,
//         banned: false,
//       },
//       gameTwo: {
//         game: "Valkyria Chronicles",
//         hallOfGreat: 2,
//         votesGiven: 1,
//         victory: false,
//         banned: false,
//       },
//       gameThree: {
//         game: "Xenoblade Chronicles",
//         hallOfGreat: 3,
//         votesGiven: 3,
//         victory: false,
//         banned: false,
//       },
//       gameFour: {
//         game: "Mega Man X",
//         hallOfGreat: 4,
//         votesGiven: 7,
//         victory: false,
//         banned: false,
//       },
//       gameFive: {
//         game: "Resident Evil Remake",
//         hallOfGreat: 5,
//         votesGiven: 11,
//         victory: true,
//         banned: false,
//       },
//       gameSix: {
//         game: "Paper Mario & The Thousand-Year Door",
//         hallOfGreat: 6,
//         votesGiven: 12,
//         victory: true,
//         banned: false,
//       },
//       gameSeven: {
//         game: "Halo: Combat Evolved",
//         hallOfGreat: 7,
//         votesGiven: 3,
//         victory: false,
//         banned: false,
//       },
//       gameEight: {
//         game: "Pikmin",
//         hallOfGreat: 8,
//         votesGiven: 2,
//         victory: false,
//         banned: false,
//       },
//       gameNine: {
//         game: "Final Fantasy IX",
//         hallOfGreat: 9,
//         votesGiven: 11,
//         victory: false,
//         banned: false,
//       },
//       gameTen: {
//         game: "Phantasy Star Online",
//         hallOfGreat: 10,
//         votesGiven: 8,
//         victory: false,
//         banned: false,
//       },
//       gameEleven: {
//         game: "Counter-Strike",
//         hallOfGreat: 11,
//         votesGiven: 15,
//         victory: true,
//         banned: false,
//       },
//       gameTwelve: {
//         game: "The Ultimate Doom",
//         hallOfGreat: 12,
//         votesGiven: 11,
//         victory: true,
//         banned: false,
//       },
//       gameThirteen: {
//         game: "Bayonetta",
//         hallOfGreat: 13,
//         votesGiven: 9,
//         victory: false,
//         banned: false,
//       },
//     },
//     allySeven: {
//       nominator: "Michael Damiani",
//       gameOne: {
//         game: "Metal Gear Solid",
//         hallOfGreat: 1,
//         votesGiven: 10,
//         victory: true,
//         banned: false,
//       },
//       gameTwo: {
//         game: "Super Mario 64",
//         hallOfGreat: 2,
//         votesGiven: 15,
//         victory: true,
//         banned: false,
//       },
//       gameThree: {
//         game: "The Legend of Zelda: Ocarina of Time",
//         hallOfGreat: 3,
//         votesGiven: 16,
//         victory: true,
//         banned: false,
//       },
//       gameFour: {
//         game: "Skyrim",
//         hallOfGreat: 4,
//         votesGiven: 0,
//         victory: false,
//         banned: true,
//       },
//       gameFive: {
//         game: "Shadow of the Colossus",
//         hallOfGreat: 5,
//         votesGiven: 1,
//         victory: false,
//         banned: false,
//       },
//       gameSix: {
//         game: "Metroid Prime",
//         hallOfGreat: 6,
//         votesGiven: 19,
//         victory: true,
//         banned: false,
//       },
//       gameSeven: {
//         game: "Super Mario RPG",
//         hallOfGreat: 7,
//         votesGiven: 2,
//         victory: false,
//         banned: false,
//       },
//       gameEight: {
//         game: "FTL: Faster Than Light",
//         hallOfGreat: 8,
//         votesGiven: 0,
//         victory: false,
//         banned: true,
//       },
//       gameNine: {
//         game: "The Legend of Zelda: A Link to the Past",
//         hallOfGreat: 9,
//         votesGiven: 13,
//         victory: true,
//         banned: false,
//       },
//       gameTen: {
//         game: "Bioshock",
//         hallOfGreat: 10,
//         votesGiven: 6,
//         victory: false,
//         banned: false,
//       },
//       gameEleven: {
//         game: "Teenage Mutant Ninja Turtles: Turtles in Time",
//         hallOfGreat: 12,
//         votesGiven: 3,
//         victory: false,
//         banned: false,
//       },
//       gameTwelve: {
//         game: "Metal Gear Rising: Revengeance",
//         hallOfGreat: 13,
//         votesGiven: 2,
//         victory: false,
//         banned: false,
//       },
//     },
//     allyEight: {
//       nominator: "Ian Hinck",
//       gameOne: {
//         game: "Bloodborne",
//         hallOfGreat: 1,
//         votesGiven: 3,
//         victory: false,
//         banned: false,
//       },
//       gameTwo: {
//         game: "Castlevania: Symphony of the Night",
//         hallOfGreat: 2,
//         votesGiven: 12,
//         victory: false,
//         banned: false,
//       },
//       gameThree: {
//         game: "Castlevania: Symphony of the Night",
//         hallOfGreat: 3,
//         votesGiven: 11,
//         victory: true,
//         banned: false,
//       },
//       gameFour: {
//         game: "Myst",
//         hallOfGreat: 4,
//         votesGiven: 2,
//         victory: false,
//         banned: false,
//       },
//       gameFive: {
//         game: "Dungeons & Dragons",
//         hallOfGreat: 5,
//         votesGiven: 0,
//         victory: false,
//         banned: true,
//       },
//       gameSix: {
//         game: "Silent Hill 2",
//         hallOfGreat: 6,
//         votesGiven: 8,
//         victory: false,
//         banned: false,
//       },
//       gameSeven: {
//         game: "Silent Hill 2",
//         hallOfGreat: 7,
//         votesGiven: 3,
//         victory: false,
//         banned: false,
//       },
//       gameEight: {
//         game: "Bloodborne",
//         hallOfGreat: 8,
//         votesGiven: 13,
//         victory: true,
//         banned: false,
//       },
//       gameNine: {
//         game: "Dark Souls Remastered",
//         hallOfGreat: 9,
//         votesGiven: 0,
//         victory: false,
//         banned: false,
//       },
//       gameTen: {
//         game: "Final Fantasy VII",
//         hallOfGreat: 10,
//         votesGiven: 1,
//         victory: false,
//         banned: false,
//       },
//       gameEleven: {
//         game: "Metal Gear Solid 3: Snake Eater",
//         hallOfGreat: 11,
//         votesGiven: 2,
//         victory: false,
//         banned: false,
//       },
//       gameTwelve: {
//         game: "Silent Hill 2",
//         hallOfGreat: 12,
//         votesGiven: 3,
//         victory: false,
//         banned: false,
//       },
//       gameThirteen: {
//         game: "The Stanley Parable",
//         hallOfGreat: 13,
//         votesGiven: 1,
//         victory: false,
//         banned: false,
//       },
//     },
//     allyNine: {
//       nominator: "Kyle Bosman",
//       gameOne: {
//         game: "Mega Man Legends",
//         hallOfGreat: 1,
//         votesGiven: 1,
//         victory: false,
//         banned: false,
//       },
//       gameTwo: {
//         game: "The Legend of Zelda: Links Awakening DX",
//         hallOfGreat: 2,
//         votesGiven: 5,
//         victory: false,
//         banned: false,
//       },
//       gameThree: {
//         game: "Final Fantasy IX",
//         hallOfGreat: 3,
//         votesGiven: 9,
//         victory: false,
//         banned: false,
//       },
//       gameFour: {
//         game: "Pokemon Red & Blue",
//         hallOfGreat: 4,
//         votesGiven: 8,
//         victory: true,
//         banned: false,
//       },
//       gameFive: {
//         game: "Mega Man Legends",
//         hallOfGreat: 5,
//         votesGiven: 1,
//         victory: false,
//         banned: false,
//       },
//       gameSix: {
//         game: "Mega Man Legends",
//         hallOfGreat: 6,
//         votesGiven: 1,
//         victory: false,
//         banned: false,
//       },
//       gameSeven: {
//         game: "Tetris",
//         hallOfGreat: 7,
//         votesGiven: 13,
//         victory: true,
//         banned: false,
//       },
//       gameEight: {
//         game: "The Legend of Zelda: Links Awakening DX",
//         hallOfGreat: 8,
//         votesGiven: 8,
//         victory: false,
//         banned: false,
//       },
//       gameNine: {
//         game: "Super Mario Bros. 3",
//         hallOfGreat: 9,
//         votesGiven: 12,
//         victory: true,
//         banned: false,
//       },
//       gameTen: {
//         game: "Halo: Combat Evolved",
//         hallOfGreat: 10,
//         votesGiven: 6,
//         victory: false,
//         banned: false,
//       },
//       gameEleven: {
//         game: "Dungeons & Dragons",
//         hallOfGreat: 11,
//         votesGiven: 0,
//         victory: false,
//         banned: true,
//       },
//       gameTwelve: {
//         game: "Mega Man Legends",
//         hallOfGreat: 12,
//         votesGiven: 5,
//         victory: false,
//         banned: false,
//       },
//     },
//   },
// ];

db.Allies.deleteMany({})
  .then(() => db.Allies.collection.insertMany(allySeed))
  .then((data) => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });

db.Games.deleteMany({})
  .then(() => db.Games.collection.insertMany(gameSeed))
  .then((data) => {
    console.log("DATA", data);
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
